<HTML>
<b> Beatriz Barros Souza Dos Santos n04 1B</b>
<p>/HTML Oii,meu nome é Beatriz Barros.Este é o meu site,no qual criei para os meus projetos que serão lançados em breve,com eles irei desenvolver
aprendizados e técnicas novas aqui no Gihtub.Pretendo com esse site,aprender e me especializar no ramo da Robótica e na computação,além de engajar mais 
no ramo para minha vida profissional.
index.html
